### ISSUE TITLE
Looking forward to getting your papers

### ISSUE THREAD

**Issue by yuhanghanghang** [cozlopez/AnalysisMode1CracksCFRP#3]
Greetings.
 I would like to ask if I can get your papers or help documents. If I can use them, they will be of great help to me. I would appreciate your reply.
Email: 3121282348@qq.com

**Comment by cozlopez** [comment]
Hello due to European Export Control Regulation the paper regarding this code might be under export limitations. As i am not fully informed on these limitation I am forced to redirect you to the Aerospace Structures and Materials department at the Delft University of Technology (TUDelft). Contact details for the department are online and available to the public. They might be able to guide you on what are the requirements to access this paper or similar kinds of research.
